### ISSUE TITLE
Bagaimana cara pakainya?

### ISSUE THREAD

**Issue by jordiyapz** [masdevid/sentistrength_id#2]
Bagaimana cara pemakaiannya?

**Comment by Yogaviw** [comment]
ka ijin bertanya, bagaiman ya cara pakainya ?

**Comment by bimacoding** [comment]
> 
> 
> ka ijin bertanya, bagaiman ya cara pakainya ?

kalau sudahmnegerti python mungkin tidak akan kesulita,
step pertama silahakn buat env pythonya
contoh saya akan membuat pada local disk D:
> windows + R
> cd D:
> git clone repo ini
> cd ke repo ini pada 
> python -m venv env
> env\Scripts\activate
> python sentistreng_id.py

selesai. semoga bisa terjawab dan gak bingung

**Comment by Yogaviw** [comment]
Oke makasih ya ka

Pada tanggal Sen, 13 Sep 2021 17.32, Arif iik ***@***.***>
menulis:

**Comment by jordiyapz** [comment]
Okey, karena sudah terjawab, saya request close saja ya. Terimakasih
